
// Data constants for registration form dropdowns

export const KENYAN_TRIBES = [
  'Bajuni',
  'Borana',
  'Chonyi',
  'Dahalo',
  'Dasanach',
  'Digo',
  'Duruma',
  'El Molo',
  'Embu',
  'Gabbra',
  'Gabra',
  'Giriama',
  'Ilchamus',
  'Kalenjin',
  'Kamba',
  'Kauma',
  'Kenyan Arabs',
  'Kikuyu',
  'Kisii',
  'Kuria',
  'Luo',
  'Luhya',
  'Maasai',
  'Marakwet',
  'Mbeere',
  'Meru',
  'Mijikenda',
  'Nandi',
  'Orma',
  'Pokomo',
  'Pokot',
  'Rabai',
  'Rendille',
  'Ribe',
  'Sabaot',
  'Samburu',
  'Somali',
  'Suba',
  'Swahili',
  'Taveta',
  'Teso',
  'Tharaka',
  'Tugen',
  'Turkana',
  'Others',
];

export const KENYAN_COUNTIES = [
  'Baringo',
  'Bomet',
  'Bungoma',
  'Busia',
  'Elgeyo-Marakwet',
  'Embu',
  'Garissa',
  'Homa Bay',
  'Isiolo',
  'Kajiado',
  'Kakamega',
  'Kericho',
  'Kiambu',
  'Kilifi',
  'Kirinyaga',
  'Kisii',
  'Kisumu',
  'Kitui',
  'Kwale',
  'Laikipia',
  'Lamu',
  'Machakos',
  'Makueni',
  'Mandera',
  'Marsabit',
  'Meru',
  'Migori',
  'Mombasa',
  'Murang\'a',
  'Nairobi',
  'Nakuru',
  'Nandi',
  'Narok',
  'Nyamira',
  'Nyandarua',
  'Nyeri',
  'Samburu',
  'Siaya',
  'Taita-Taveta',
  'Tana River',
  'Tharaka-Nithi',
  'Trans Nzoia',
  'Turkana',
  'Uasin Gishu',
  'Vihiga',
  'Wajir',
  'West Pokot',
];

// Simplified constituencies - in production, this would be filtered by county
export const CONSTITUENCIES: { [key: string]: string[] } = {
  'Nairobi': [
    'Westlands',
    'Dagoretti North',
    'Dagoretti South',
    'Langata',
    'Kibra',
    'Roysambu',
    'Kasarani',
    'Ruaraka',
    'Embakasi South',
    'Embakasi North',
    'Embakasi Central',
    'Embakasi East',
    'Embakasi West',
    'Makadara',
    'Kamukunji',
    'Starehe',
    'Mathare',
  ],
  'Mombasa': [
    'Changamwe',
    'Jomvu',
    'Kisauni',
    'Nyali',
    'Likoni',
    'Mvita',
  ],
  'Kisumu': [
    'Kisumu East',
    'Kisumu West',
    'Kisumu Central',
    'Seme',
    'Nyando',
    'Muhoroni',
    'Nyakach',
  ],
  // Add more counties and their constituencies as needed
  'Default': ['Select county first'],
};

export const COUNTRIES = [
  'Afghanistan',
  'Albania',
  'Algeria',
  'Andorra',
  'Angola',
  'Antigua and Barbuda',
  'Argentina',
  'Armenia',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Bahamas',
  'Bahrain',
  'Bangladesh',
  'Barbados',
  'Belarus',
  'Belgium',
  'Belize',
  'Benin',
  'Bhutan',
  'Bolivia',
  'Bosnia and Herzegovina',
  'Botswana',
  'Brazil',
  'Brunei',
  'Bulgaria',
  'Burkina Faso',
  'Burundi',
  'Cabo Verde',
  'Cambodia',
  'Cameroon',
  'Canada',
  'Central African Republic',
  'Chad',
  'Chile',
  'China',
  'Colombia',
  'Comoros',
  'Congo (Congo-Brazzaville)',
  'Costa Rica',
  'Croatia',
  'Cuba',
  'Cyprus',
  'Czechia (Czech Republic)',
  'Democratic Republic of the Congo',
  'Denmark',
  'Djibouti',
  'Dominica',
  'Dominican Republic',
  'Ecuador',
  'Egypt',
  'El Salvador',
  'Equatorial Guinea',
  'Eritrea',
  'Estonia',
  'Eswatini (fmr. "Swaziland")',
  'Ethiopia',
  'Fiji',
  'Finland',
  'France',
  'Gabon',
  'Gambia',
  'Georgia',
  'Germany',
  'Ghana',
  'Greece',
  'Grenada',
  'Guatemala',
  'Guinea',
  'Guinea-Bissau',
  'Guyana',
  'Haiti',
  'Holy See',
  'Honduras',
  'Hungary',
  'Iceland',
  'India',
  'Indonesia',
  'Iran',
  'Iraq',
  'Ireland',
  'Israel',
  'Italy',
  'Jamaica',
  'Japan',
  'Jordan',
  'Kazakhstan',
  'Kenya',
  'Kiribati',
  'Kuwait',
  'Kyrgyzstan',
  'Laos',
  'Latvia',
  'Lebanon',
  'Lesotho',
  'Liberia',
  'Libya',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Madagascar',
  'Malawi',
  'Malaysia',
  'Maldives',
  'Mali',
  'Malta',
  'Marshall Islands',
  'Mauritania',
  'Mauritius',
  'Mexico',
  'Micronesia',
  'Moldova',
  'Monaco',
  'Mongolia',
  'Montenegro',
  'Morocco',
  'Mozambique',
  'Myanmar (formerly Burma)',
  'Namibia',
  'Nauru',
  'Nepal',
  'Netherlands',
  'New Zealand',
  'Nicaragua',
  'Niger',
  'Nigeria',
  'North Korea',
  'North Macedonia',
  'Norway',
  'Oman',
  'Pakistan',
  'Palau',
  'Palestine State',
  'Panama',
  'Papua New Guinea',
  'Paraguay',
  'Peru',
  'Philippines',
  'Poland',
  'Portugal',
  'Qatar',
  'Romania',
  'Russia',
  'Rwanda',
  'Saint Kitts and Nevis',
  'Saint Lucia',
  'Saint Vincent and the Grenadines',
  'Samoa',
  'San Marino',
  'Sao Tome and Principe',
  'Saudi Arabia',
  'Senegal',
  'Serbia',
  'Seychelles',
  'Sierra Leone',
  'Singapore',
  'Slovakia',
  'Slovenia',
  'Solomon Islands',
  'Somalia',
  'South Africa',
  'South Korea',
  'South Sudan',
  'Spain',
  'Sri Lanka',
  'Sudan',
  'Suriname',
  'Sweden',
  'Switzerland',
  'Syria',
  'Taiwan',
  'Tajikistan',
  'Tanzania',
  'Thailand',
  'Timor-Leste',
  'Togo',
  'Tonga',
  'Trinidad and Tobago',
  'Tunisia',
  'Turkey',
  'Turkmenistan',
  'Tuvalu',
  'Uganda',
  'Ukraine',
  'United Arab Emirates',
  'United Kingdom',
  'United States',
  'Uruguay',
  'Uzbekistan',
  'Vanuatu',
  'Venezuela',
  'Vietnam',
  'Yemen',
  'Zambia',
  'Zimbabwe',
];

export const NATIONALITIES = [
  'Kenyan',
  'Ugandan',
  'Tanzanian',
  'Rwandan',
  'Burundian',
  'South Sudanese',
  'Ethiopian',
  'Somali',
  'American',
  'British',
  'Canadian',
  'Australian',
  'South African',
  'Nigerian',
  'Ghanaian',
  'Other',
];

export const GENDERS = ['Male', 'Female'];

export const SEXUAL_ORIENTATIONS = [
  'Heterosexual',
  'Homosexual',
  'Bisexual',
  'Pansexual',
  'Asexual',
  'Other',
];

export const RELATIONSHIP_GOALS = [
  'Casual',
  'Serious relationship leading to marriage',
  'Marriage',
  'Long-term relationship',
  'Short-term relationship',
  'Friendship',
  'Not sure yet',
];

export const RELIGIONS = [
  'Christianity',
  'Islam',
  'Hinduism',
  'Buddhism',
  'Judaism',
  'Traditional African religion',
  'Atheist / Agnostic',
  'Other',
  'Prefer not to say',
];

export const RELIGIOUSNESS_LEVELS = [
  'Very religious',
  'Moderately religious',
  'Slightly religious',
  'Not religious',
];

export const YES_NO_OPTIONS = ['Yes', 'No'];

export const COMPLEXIONS = [
  'Very fair',
  'Fair',
  'Medium',
  'Olive',
  'Brown',
  'Dark brown',
  'Very dark',
  'Medium brown (warm cocoa or bronze tone)',
];

export const TEETH_STATUS_OPTIONS = [
  'White and well aligned',
  'Stained',
  'Chipped or cracked',
  'Missing teeth',
  'Crooked or misaligned',
];

export const HIV_STATUS_OPTIONS = ['Negative', 'Positive'];

export const BLOOD_GROUPS = [
  'A+',
  'A−',
  'B+',
  'B−',
  'AB+',
  'AB−',
  'O+',
  'O−',
  'I don\'t know',
];

export const YES_NO_OCCASIONALLY = ['Yes', 'No', 'Occasionally'];

export const EDUCATION_LEVELS = [
  'Primary education',
  'Secondary education',
  'Diploma or certificate',
  'Bachelor\'s degree',
  'Master\'s degree',
  'Doctorate (PhD)',
  'Other',
];

export const EMPLOYMENT_STATUS_OPTIONS = [
  'Employed full-time',
  'Employed part-time',
  'Self-employed',
  'Unemployed',
  'Student',
  'Retired',
];

export const FINANCIAL_STABILITY_OPTIONS = [
  'Very stable',
  'Stable',
  'Getting by',
  'Struggling',
];

export const YES_NO_MAYBE = ['Yes', 'No', 'Maybe'];

export const MARITAL_STATUS_OPTIONS = [
  'Single',
  'Divorced',
  'Widowed',
  'Widower',
  'Married',
  'Separated',
];

export const RELATIONSHIP_PERSPECTIVES = [
  'Traditional (man leads)',
  'Modern (woman leads)',
  'Shared roles / equal partnership',
];

// Body type images would be stored in assets and referenced here
export const MALE_BODY_TYPES = [
  { id: 'slim', label: 'Slim', image: 'male_slim' },
  { id: 'athletic', label: 'Athletic', image: 'male_athletic' },
  { id: 'average', label: 'Average', image: 'male_average' },
  { id: 'muscular', label: 'Muscular', image: 'male_muscular' },
  { id: 'heavyset', label: 'Heavyset', image: 'male_heavyset' },
];

export const FEMALE_BODY_TYPES = [
  { id: 'slim', label: 'Slim', image: 'female_slim' },
  { id: 'athletic', label: 'Athletic', image: 'female_athletic' },
  { id: 'average', label: 'Average', image: 'female_average' },
  { id: 'curvy', label: 'Curvy', image: 'female_curvy' },
  { id: 'plus_size', label: 'Plus Size', image: 'female_plus_size' },
];
